/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FriendRequest } from '../../models/friend-request';

export interface GetPendingRequests$Params {
  username: string;
}

export function getPendingRequests(http: HttpClient, rootUrl: string, params: GetPendingRequests$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FriendRequest>>> {
  const rb = new RequestBuilder(rootUrl, getPendingRequests.PATH, 'get');
  if (params) {
    rb.query('username', params.username, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<FriendRequest>>;
    })
  );
}

getPendingRequests.PATH = '/friends/requests';
