/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getUnreadNotifications } from '../fn/notification/get-unread-notifications';
import { GetUnreadNotifications$Params } from '../fn/notification/get-unread-notifications';
import { markNotificationAsRead } from '../fn/notification/mark-notification-as-read';
import { MarkNotificationAsRead$Params } from '../fn/notification/mark-notification-as-read';
import { Notification } from '../models/notification';

@Injectable({ providedIn: 'root' })
export class NotificationService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `markNotificationAsRead()` */
  static readonly MarkNotificationAsReadPath = '/notifications/{id}/read';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `markNotificationAsRead()` instead.
   *
   * This method doesn't expect any request body.
   */
  markNotificationAsRead$Response(params: MarkNotificationAsRead$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return markNotificationAsRead(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `markNotificationAsRead$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  markNotificationAsRead(params: MarkNotificationAsRead$Params, context?: HttpContext): Observable<string> {
    return this.markNotificationAsRead$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `getUnreadNotifications()` */
  static readonly GetUnreadNotificationsPath = '/notifications/unread';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUnreadNotifications()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUnreadNotifications$Response(params: GetUnreadNotifications$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Notification>>> {
    return getUnreadNotifications(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUnreadNotifications$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUnreadNotifications(params: GetUnreadNotifications$Params, context?: HttpContext): Observable<Array<Notification>> {
    return this.getUnreadNotifications$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Notification>>): Array<Notification> => r.body)
    );
  }

}
