/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ContactRequest {
  description?: string;
  email: string;
  id?: number;
  name: string;
  phone: string;
  secondName: string;
  work: string;
}
