/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ContactResponse {
  description?: string;
  email?: string;
  id?: number;
  image?: string;
  name?: string;
  phone?: string;
  secondName?: string;
  work?: string;
}
