/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Contact {
  createdBy?: number;
  createdDate?: string;
  description?: string;
  email?: string;
  id?: number;
  image?: string;
  lastModifiedBy?: number;
  lastModifiedDate?: string;
  name?: string;
  phone?: string;
  secondName?: string;
  work?: string;
}
