/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface FriendRequest {
  id?: number;
  receiver?: User;
  sender?: User;
  status?: 'PENDING' | 'ACCEPTED' | 'DECLINED';
}
