/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface Notification {
  createdAt?: string;
  id?: number;
  message?: string;
  read?: boolean;
  recipient?: User;
}
