/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PostResponse {
  content?: string;
  id?: number;
  imageName?: string;
  title?: string;
  user?: string;
}
