/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Comment } from '../models/comment';
import { User } from '../models/user';
export interface Post {
  comments?: Array<Comment>;
  content?: string;
  createdBy?: number;
  createdDate?: string;
  id?: number;
  imageName?: string;
  lastModifiedBy?: number;
  lastModifiedDate?: string;
  title?: string;
  user?: User;
}
