/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Book } from '../models/book';
import { BookTransactionHistory } from '../models/book-transaction-history';
import { Contact } from '../models/contact';
import { Post } from '../models/post';
import { Role } from '../models/role';
export interface User {
  accountLocked?: boolean;
  books?: Array<Book>;
  contact?: Array<Contact>;
  createdDate?: string;
  dateOfBrith?: string;
  email?: string;
  enabled?: boolean;
  firstname?: string;
  friends?: Array<User>;
  histories?: Array<BookTransactionHistory>;
  id?: number;
  lastModifiedDate?: string;
  lastname?: string;
  password?: string;
  posts?: Array<Post>;
  roles?: Array<Role>;
}
