/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserResponse {
  accountLocked?: boolean;
  dateOfBrith?: string;
  email?: string;
  enabled?: boolean;
  firstname?: string;
  id?: number;
  lastname?: string;
}
