/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ContactResponse } from '../../models/contact-response';

export interface GetContactById$Params {
  'contact-id': number;
}

export function getContactById(http: HttpClient, rootUrl: string, params: GetContactById$Params, context?: HttpContext): Observable<StrictHttpResponse<ContactResponse>> {
  const rb = new RequestBuilder(rootUrl, getContactById.PATH, 'get');
  if (params) {
    rb.path('contact-id', params['contact-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ContactResponse>;
    })
  );
}

getContactById.PATH = '/contacts/{contact-id}';
